name: Deploy CursedVibes API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: cursedvibes-webapi
          slot-name: production
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ./CursedVibes.WebAPI/bin/Release/net9.0
