name: Deploy CursedVibes API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish WebAPI
        run: dotnet publish ./CursedVibes.WebAPI/CursedVibes.WebAPI.csproj --configuration Release --output ./publish

      - name: Run tests
        run: dotnet test ./CursedVibes.Tests/CursedVibes.Tests.csproj --configuration Release --verbosity normal

      - name: List publish folder (debug)
        run: ls -la ./publish

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy using Azure CLI
        run: |
          az webapp deploy --name cursedvibes-webapi \
                           --resource-group BackendDev-EU-RG \
                           --src-path ./publish \
                           --type zip
