name: Test CursedVibes API (Dev)

on:
  push:
    branches:
      - dev

jobs:
  test-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test ./CursedVibes.Tests/CursedVibes.Tests.csproj --configuration Release --verbosity detailed
